version: 2.1
orbs:
  node: circleci/node:lts-browsers
jobs:
  build:
    environment:
      CI: true
      CODECOV_TOKEN: f913a653-4fee-4054-87a1-6fbba988bcef
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm ci
      - run:
          name: build
          command: npm run build
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
      - run:
          name: Code cov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
